/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 24-Nov-2019 19:24:30
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 62
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define LPL 61
Int16 LP[61] = {
      4807,    199,    201,    206,    209,    213,    215,    219,    222,
       225,    228,    232,    234,    237,    239,    242,    243,    246,
       248,    252,    251,    251,    257,    258,    258,    258,    258,
       258,    258,    258,    258,    258,    258,    258,    258,    258,
       258,    258,    257,    251,    251,    252,    248,    246,    243,
       242,    239,    237,    234,    232,    228,    225,    222,    219,
       215,    213,    209,    206,    201,    199,   4807
};
